# Generated by Django 3.2.1 on 2021-05-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.meet')),
            ],
        ),
    ]
