# Generated by Django 3.2.1 on 2021-05-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.AddField(
            model_name='meet',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
