# Generated by Django 3.2.1 on 2021-05-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210515_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='msg',
        ),
    ]
