# Generated by Django 3.2.1 on 2021-05-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_content_message_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='msg',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default='abcd', max_length=150),
        ),
    ]
