# Generated by Django 3.2.1 on 2021-05-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='meet',
        ),
    ]
