# Generated by Django 3.2.1 on 2021-05-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_message_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='meet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.meet'),
        ),
    ]
