# Generated by Django 3.2.1 on 2021-05-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_message_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='code',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.meet'),
        ),
    ]
