# Generated by Django 3.2.1 on 2021-05-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_message_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buffer',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('code', models.CharField(max_length=15)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.meet')),
            ],
        ),
    ]
